# Generated by Django 5.2 on 2026-08-12 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', models.ImageField(upload_to='wallpapers/', verbose_name='Image')),
                ('category', models.CharField(choices=[('city_view', 'City View'), ('animation', 'Animation'), ('nature', 'Nature'), ('space', 'Space')], max_length=50, verbose_name='Category')),
                ('resolution', models.CharField(max_length=50, verbose_name='Resolution')),
                ('format', models.CharField(choices=[('jpeg', 'JPEG'), ('png', 'PNG'), ('webp', 'WebP')], max_length=20, verbose_name='Format')),
                ('filesize', models.CharField(max_length=50, verbose_name='File Size')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('download_count', models.IntegerField(default=0, verbose_name='Download Count')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_wallpapers', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Wallpaper',
                'verbose_name_plural': 'Wallpapers',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Bookmarked At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('wallpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='listings.wallpaper', verbose_name='Wallpaper')),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'unique_together': {('user', 'wallpaper')},
            },
        ),
    ]
