# Generated by Django 5.2 on 2026-08-18 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaper',
            name='description',
        ),
    ]
